bot command proxy, conf directory, bitly api key handling, etc.
Summary of changes:

- Implement proxy pattern for bot commands so we can authorize the command before running it.
- Move most of the properties files into a conf dirctory and include it in the archive during the package lifecycle.
- Fix NoClassDefFoundError exception when running the bot outside the IDE.
- Fallback to BITLY_API_ENDPOINT and BITLY_API_KEY environment variables if not present in properties file and remove my personal key from default properties file.
- Other miscalleneous changes.